package explain

// DangerLevel classifies flag destructiveness.
type DangerLevel string

const (
	Safe        DangerLevel = "safe"
	Caution     DangerLevel = "caution"
	Destructive DangerLevel = "destructive"
)

// FlagInfo describes a single flag for a tool.
type FlagInfo struct {
	Short       string
	Long        string
	Description string
	Danger      DangerLevel
	Tip         string // optional safety tip
}

// ToolInfo describes a CLI tool.
type ToolInfo struct {
	Name        string
	Description string
	Flags       map[string]FlagInfo // keyed by flag string (e.g., "-f", "--force")
	Subcommands map[string]string   // subcommand -> description
}

// flagDB is the compiled flag database, keyed by binary name.
var flagDB = map[string]ToolInfo{
	"find": {
		Name:        "find",
		Description: "search for files in a directory hierarchy",
		Flags: map[string]FlagInfo{
			"-name":    {Long: "-name", Description: "match files by name pattern", Danger: Safe},
			"-iname":   {Long: "-iname", Description: "match files by name pattern (case-insensitive)", Danger: Safe},
			"-type":    {Long: "-type", Description: "filter by type (f=file, d=directory, l=symlink)", Danger: Safe},
			"-size":    {Long: "-size", Description: "filter by size (+N = larger, -N = smaller)", Danger: Safe},
			"-mtime":   {Long: "-mtime", Description: "filter by modification time in days (+N = older, -N = newer)", Danger: Safe},
			"-atime":   {Long: "-atime", Description: "filter by access time in days", Danger: Safe},
			"-ctime":   {Long: "-ctime", Description: "filter by change time in days", Danger: Safe},
			"-mmin":    {Long: "-mmin", Description: "filter by modification time in minutes", Danger: Safe},
			"-maxdepth": {Long: "-maxdepth", Description: "limit search depth", Danger: Safe},
			"-mindepth": {Long: "-mindepth", Description: "minimum search depth", Danger: Safe},
			"-exec":    {Long: "-exec", Description: "execute command on each match", Danger: Caution, Tip: "Verify matches with -print first"},
			"-delete":  {Long: "-delete", Description: "permanently delete matching files", Danger: Destructive, Tip: "Remove -delete and add -print first to preview"},
			"-print":   {Long: "-print", Description: "print matching file paths (default)", Danger: Safe},
			"-print0":  {Long: "-print0", Description: "print paths null-delimited (for xargs -0)", Danger: Safe},
			"-path":    {Long: "-path", Description: "match against full path pattern", Danger: Safe},
			"-not":     {Long: "-not", Description: "negate the following expression", Danger: Safe},
			"-o":       {Short: "-o", Description: "logical OR between expressions", Danger: Safe},
			"-a":       {Short: "-a", Description: "logical AND between expressions (default)", Danger: Safe},
			"-perm":    {Long: "-perm", Description: "filter by permissions", Danger: Safe},
			"-user":    {Long: "-user", Description: "filter by owner user", Danger: Safe},
			"-group":   {Long: "-group", Description: "filter by owner group", Danger: Safe},
			"-empty":   {Long: "-empty", Description: "match empty files or directories", Danger: Safe},
			"-newer":   {Long: "-newer", Description: "match files newer than given file", Danger: Safe},
			"-regex":   {Long: "-regex", Description: "match path against regex", Danger: Safe},
			"-ls":      {Long: "-ls", Description: "list matches in ls -l format", Danger: Safe},
			"-prune":   {Long: "-prune", Description: "skip descending into matched directory", Danger: Safe},
		},
	},
	"tar": {
		Name:        "tar",
		Description: "archive and extract files",
		Flags: map[string]FlagInfo{
			"-c":  {Short: "-c", Long: "--create", Description: "create a new archive", Danger: Safe},
			"-x":  {Short: "-x", Long: "--extract", Description: "extract files from archive", Danger: Caution, Tip: "May overwrite existing files"},
			"-t":  {Short: "-t", Long: "--list", Description: "list contents of archive", Danger: Safe},
			"-z":  {Short: "-z", Long: "--gzip", Description: "compress/decompress with gzip", Danger: Safe},
			"-j":  {Short: "-j", Long: "--bzip2", Description: "compress/decompress with bzip2", Danger: Safe},
			"-J":  {Short: "-J", Long: "--xz", Description: "compress/decompress with xz", Danger: Safe},
			"-v":  {Short: "-v", Long: "--verbose", Description: "show files being processed", Danger: Safe},
			"-f":  {Short: "-f", Long: "--file", Description: "archive file name", Danger: Safe},
			"-C":  {Short: "-C", Long: "--directory", Description: "change to directory before operation", Danger: Safe},
			"--exclude": {Long: "--exclude", Description: "exclude files matching pattern", Danger: Safe},
			"-p":  {Short: "-p", Long: "--preserve-permissions", Description: "preserve file permissions", Danger: Safe},
			"--strip-components": {Long: "--strip-components", Description: "strip N leading path components on extract", Danger: Safe},
			"-r":  {Short: "-r", Long: "--append", Description: "append files to archive", Danger: Safe},
			"-u":  {Short: "-u", Long: "--update", Description: "only append newer files", Danger: Safe},
			"--create":  {Long: "--create", Description: "create a new archive", Danger: Safe},
			"--extract": {Long: "--extract", Description: "extract files from archive", Danger: Caution},
			"--gzip":    {Long: "--gzip", Description: "compress/decompress with gzip", Danger: Safe},
			"--verbose": {Long: "--verbose", Description: "show files being processed", Danger: Safe},
			"--file":    {Long: "--file", Description: "archive file name", Danger: Safe},
		},
	},
	"grep": {
		Name:        "grep",
		Description: "search text patterns in files",
		Flags: map[string]FlagInfo{
			"-r":  {Short: "-r", Long: "--recursive", Description: "search directories recursively", Danger: Safe},
			"-R":  {Short: "-R", Description: "search recursively, following symlinks", Danger: Safe},
			"-n":  {Short: "-n", Long: "--line-number", Description: "show line numbers", Danger: Safe},
			"-i":  {Short: "-i", Long: "--ignore-case", Description: "case-insensitive matching", Danger: Safe},
			"-v":  {Short: "-v", Long: "--invert-match", Description: "invert match (show non-matching lines)", Danger: Safe},
			"-l":  {Short: "-l", Long: "--files-with-matches", Description: "show only filenames of matches", Danger: Safe},
			"-L":  {Short: "-L", Description: "show filenames without matches", Danger: Safe},
			"-c":  {Short: "-c", Long: "--count", Description: "show count of matching lines per file", Danger: Safe},
			"-w":  {Short: "-w", Long: "--word-regexp", Description: "match whole words only", Danger: Safe},
			"-E":  {Short: "-E", Long: "--extended-regexp", Description: "use extended regex (ERE)", Danger: Safe},
			"-P":  {Short: "-P", Long: "--perl-regexp", Description: "use Perl-compatible regex", Danger: Safe},
			"-o":  {Short: "-o", Long: "--only-matching", Description: "show only matching parts", Danger: Safe},
			"-A":  {Short: "-A", Long: "--after-context", Description: "show N lines after match", Danger: Safe},
			"-B":  {Short: "-B", Long: "--before-context", Description: "show N lines before match", Danger: Safe},
			"-C":  {Short: "-C", Long: "--context", Description: "show N lines around match", Danger: Safe},
			"--include": {Long: "--include", Description: "search only files matching pattern", Danger: Safe},
			"--exclude": {Long: "--exclude", Description: "skip files matching pattern", Danger: Safe},
			"--exclude-dir": {Long: "--exclude-dir", Description: "skip directories matching pattern", Danger: Safe},
			"-q":  {Short: "-q", Long: "--quiet", Description: "suppress output (exit code only)", Danger: Safe},
			"-s":  {Short: "-s", Long: "--no-messages", Description: "suppress error messages", Danger: Safe},
			"--color": {Long: "--color", Description: "colorize matching text", Danger: Safe},
		},
	},
	"sed": {
		Name:        "sed",
		Description: "stream editor for text transformation",
		Flags: map[string]FlagInfo{
			"-i":  {Short: "-i", Long: "--in-place", Description: "edit files in place", Danger: Caution, Tip: "Use -i.bak to create backups"},
			"-e":  {Short: "-e", Long: "--expression", Description: "add editing expression", Danger: Safe},
			"-n":  {Short: "-n", Long: "--quiet", Description: "suppress automatic output", Danger: Safe},
			"-r":  {Short: "-r", Long: "--regexp-extended", Description: "use extended regex", Danger: Safe},
			"-E":  {Short: "-E", Description: "use extended regex (POSIX)", Danger: Safe},
			"-f":  {Short: "-f", Long: "--file", Description: "read expressions from file", Danger: Safe},
		},
	},
	"awk": {
		Name:        "awk",
		Description: "pattern scanning and text processing",
		Flags: map[string]FlagInfo{
			"-F":  {Short: "-F", Long: "--field-separator", Description: "set field separator", Danger: Safe},
			"-v":  {Short: "-v", Description: "set variable before execution", Danger: Safe},
			"-f":  {Short: "-f", Description: "read program from file", Danger: Safe},
		},
	},
	"git": {
		Name:        "git",
		Description: "distributed version control system",
		Subcommands: map[string]string{
			"init":     "initialize a new repository",
			"clone":    "clone a repository",
			"add":      "stage changes for commit",
			"commit":   "record changes to the repository",
			"push":     "upload local commits to remote",
			"pull":     "fetch and merge from remote",
			"fetch":    "download objects and refs from remote",
			"merge":    "join two or more development histories",
			"rebase":   "reapply commits on top of another base",
			"checkout": "switch branches or restore files",
			"switch":   "switch branches",
			"branch":   "list, create, or delete branches",
			"status":   "show working tree status",
			"log":      "show commit logs",
			"diff":     "show changes between commits/files",
			"stash":    "stash changes temporarily",
			"tag":      "create, list, or delete tags",
			"remote":   "manage tracked repositories",
			"reset":    "reset current HEAD to a specified state",
			"revert":   "create a commit that undoes a previous commit",
			"cherry-pick": "apply specific commits from another branch",
			"bisect":   "binary search to find commit that introduced a bug",
			"blame":    "show who changed each line of a file",
			"show":     "show various types of objects",
			"rm":       "remove files from working tree and index",
			"mv":       "move or rename a file",
			"clean":    "remove untracked files from working tree",
			"restore":  "restore working tree files",
			"worktree": "manage multiple working trees",
			"submodule": "manage submodules",
		},
		Flags: map[string]FlagInfo{
			"-m":        {Short: "-m", Description: "commit message", Danger: Safe},
			"--amend":   {Long: "--amend", Description: "amend the previous commit", Danger: Caution, Tip: "Don't amend published commits"},
			"-f":        {Short: "-f", Long: "--force", Description: "force operation", Danger: Destructive, Tip: "Use --force-with-lease for push to prevent overwriting others' work"},
			"--force":   {Long: "--force", Description: "force operation", Danger: Destructive, Tip: "Use --force-with-lease for push"},
			"--force-with-lease": {Long: "--force-with-lease", Description: "force push only if remote hasn't changed", Danger: Caution},
			"-b":        {Short: "-b", Description: "create and switch to new branch", Danger: Safe},
			"-d":        {Short: "-d", Description: "delete branch (only if merged)", Danger: Caution},
			"-D":        {Short: "-D", Description: "force delete branch", Danger: Destructive, Tip: "This deletes the branch even if unmerged"},
			"--hard":    {Long: "--hard", Description: "reset working tree and index (discard changes)", Danger: Destructive, Tip: "This discards uncommitted changes permanently"},
			"--soft":    {Long: "--soft", Description: "reset HEAD only (keep changes staged)", Danger: Safe},
			"--mixed":   {Long: "--mixed", Description: "reset HEAD and index (keep working tree)", Danger: Caution},
			"--oneline": {Long: "--oneline", Description: "show each commit on one line", Danger: Safe},
			"--graph":   {Long: "--graph", Description: "show ASCII commit graph", Danger: Safe},
			"--all":     {Long: "--all", Description: "include all branches", Danger: Safe},
			"-a":        {Short: "-a", Description: "stage all tracked modified files", Danger: Safe},
			"-A":        {Short: "-A", Description: "stage all changes (including untracked)", Danger: Safe},
			"-p":        {Short: "-p", Long: "--patch", Description: "interactively stage chunks", Danger: Safe},
			"--stat":    {Long: "--stat", Description: "show diffstat summary", Danger: Safe},
			"--cached":  {Long: "--cached", Description: "operate on staged changes", Danger: Safe},
			"--no-ff":   {Long: "--no-ff", Description: "create merge commit even for fast-forward", Danger: Safe},
			"--squash":  {Long: "--squash", Description: "squash commits during merge", Danger: Caution},
			"--abort":   {Long: "--abort", Description: "abort current merge/rebase", Danger: Safe},
			"--continue": {Long: "--continue", Description: "continue after resolving conflicts", Danger: Safe},
			"--rebase":  {Long: "--rebase", Description: "rebase instead of merge on pull", Danger: Safe},
			"-n":        {Short: "-n", Long: "--dry-run", Description: "dry run (show what would happen)", Danger: Safe},
			"--short":   {Long: "--short", Description: "show output in short format", Danger: Safe},
			"--porcelain": {Long: "--porcelain", Description: "machine-readable output", Danger: Safe},
			"-u":        {Short: "-u", Description: "set upstream tracking branch", Danger: Safe},
			"--set-upstream-to": {Long: "--set-upstream-to", Description: "set upstream tracking branch", Danger: Safe},
			"--no-edit": {Long: "--no-edit", Description: "use default commit message", Danger: Safe},
			"-v":        {Short: "-v", Long: "--verbose", Description: "be more verbose", Danger: Safe},
			"--depth":   {Long: "--depth", Description: "create a shallow clone with N commits", Danger: Safe},
			"--single-branch": {Long: "--single-branch", Description: "clone only one branch", Danger: Safe},
			"--recursive": {Long: "--recursive", Description: "initialize submodules recursively", Danger: Safe},
		},
	},
	"docker": {
		Name:        "docker",
		Description: "container platform",
		Subcommands: map[string]string{
			"run":       "run a new container",
			"exec":      "execute a command in a running container",
			"build":     "build an image from a Dockerfile",
			"pull":      "pull an image from a registry",
			"push":      "push an image to a registry",
			"ps":        "list containers",
			"images":    "list images",
			"rm":        "remove containers",
			"rmi":       "remove images",
			"stop":      "stop running containers",
			"start":     "start stopped containers",
			"restart":   "restart containers",
			"logs":      "fetch container logs",
			"inspect":   "show container/image details",
			"network":   "manage networks",
			"volume":    "manage volumes",
			"compose":   "multi-container orchestration",
			"system":    "manage Docker",
			"container": "manage containers",
			"image":     "manage images",
			"tag":       "tag an image",
			"login":     "log in to a registry",
			"logout":    "log out from a registry",
			"cp":        "copy files between container and host",
			"stats":     "show container resource usage",
			"top":       "show running processes in container",
			"port":      "list port mappings",
			"diff":      "show changes in container filesystem",
			"commit":    "create image from container",
			"save":      "save image to tar archive",
			"load":      "load image from tar archive",
			"export":    "export container filesystem as tar",
			"import":    "import container filesystem",
		},
		Flags: map[string]FlagInfo{
			"-d":         {Short: "-d", Long: "--detach", Description: "run in background", Danger: Safe},
			"-it":        {Short: "-it", Description: "interactive terminal (stdin + TTY)", Danger: Safe},
			"-i":         {Short: "-i", Long: "--interactive", Description: "keep stdin open", Danger: Safe},
			"-t":         {Short: "-t", Long: "--tty", Description: "allocate a pseudo-TTY", Danger: Safe},
			"-p":         {Short: "-p", Long: "--publish", Description: "map port host:container", Danger: Safe},
			"-v":         {Short: "-v", Long: "--volume", Description: "mount volume host:container", Danger: Safe},
			"-e":         {Short: "-e", Long: "--env", Description: "set environment variable", Danger: Safe},
			"--name":     {Long: "--name", Description: "assign container name", Danger: Safe},
			"--rm":       {Long: "--rm", Description: "auto-remove container on exit", Danger: Safe},
			"-f":         {Short: "-f", Long: "--force", Description: "force removal", Danger: Destructive},
			"--force":    {Long: "--force", Description: "force removal", Danger: Destructive},
			"-a":         {Short: "-a", Long: "--all", Description: "include stopped containers/all tags", Danger: Safe},
			"--all":      {Long: "--all", Description: "include stopped containers/all tags", Danger: Safe},
			"-q":         {Short: "-q", Long: "--quiet", Description: "show only IDs", Danger: Safe},
			"--no-cache": {Long: "--no-cache", Description: "build without cache", Danger: Safe},
			"--build-arg": {Long: "--build-arg", Description: "set build-time variable", Danger: Safe},
			"--network":  {Long: "--network", Description: "connect to network", Danger: Safe},
			"--restart":  {Long: "--restart", Description: "restart policy (no/always/on-failure)", Danger: Safe},
			"--privileged": {Long: "--privileged", Description: "run with full host privileges", Danger: Destructive, Tip: "Container has full access to host — use with extreme caution"},
			"--tail":     {Long: "--tail", Description: "show last N log lines", Danger: Safe},
			"--follow":   {Long: "--follow", Description: "follow log output", Danger: Safe},
			"-af":        {Short: "-af", Description: "all + force (remove all forcefully)", Danger: Destructive},
			"--prune":    {Long: "--prune", Description: "remove unused resources", Danger: Destructive, Tip: "This removes all stopped containers, unused networks, dangling images"},
			"-w":         {Short: "-w", Long: "--workdir", Description: "set working directory inside container", Danger: Safe},
			"--platform": {Long: "--platform", Description: "set platform (linux/amd64, linux/arm64)", Danger: Safe},
		},
	},
	"kubectl": {
		Name:        "kubectl",
		Description: "Kubernetes command-line tool",
		Subcommands: map[string]string{
			"get":       "display resources",
			"describe":  "show detailed resource info",
			"create":    "create a resource",
			"apply":     "apply configuration to a resource",
			"delete":    "delete resources",
			"edit":      "edit a resource in editor",
			"exec":      "execute a command in a container",
			"logs":      "print container logs",
			"port-forward": "forward local port to pod",
			"scale":     "change number of replicas",
			"rollout":   "manage rollouts",
			"expose":    "expose a resource as a service",
			"run":       "run a pod",
			"config":    "modify kubeconfig",
			"cluster-info": "display cluster info",
			"top":       "show resource usage",
			"drain":     "drain a node for maintenance",
			"cordon":    "mark node as unschedulable",
			"uncordon":  "mark node as schedulable",
			"taint":     "update taints on nodes",
			"label":     "update labels on resources",
			"annotate":  "update annotations on resources",
			"patch":     "update fields of a resource",
			"cp":        "copy files between container and local",
		},
		Flags: map[string]FlagInfo{
			"-n":            {Short: "-n", Long: "--namespace", Description: "target namespace", Danger: Safe},
			"--namespace":   {Long: "--namespace", Description: "target namespace", Danger: Safe},
			"-o":            {Short: "-o", Long: "--output", Description: "output format (json/yaml/wide/name)", Danger: Safe},
			"--output":      {Long: "--output", Description: "output format (json/yaml/wide/name)", Danger: Safe},
			"-l":            {Short: "-l", Long: "--selector", Description: "label selector filter", Danger: Safe},
			"--selector":    {Long: "--selector", Description: "label selector filter", Danger: Safe},
			"-A":            {Short: "-A", Long: "--all-namespaces", Description: "search across all namespaces", Danger: Safe},
			"--all-namespaces": {Long: "--all-namespaces", Description: "search across all namespaces", Danger: Safe},
			"-f":            {Short: "-f", Long: "--filename", Description: "config file or directory", Danger: Safe},
			"--filename":    {Long: "--filename", Description: "config file or directory", Danger: Safe},
			"--force":       {Long: "--force", Description: "force deletion (immediate, no grace period)", Danger: Destructive, Tip: "Use --grace-period=0 with care — pods may not shut down cleanly"},
			"--grace-period": {Long: "--grace-period", Description: "seconds to wait before force-kill", Danger: Caution},
			"-w":            {Short: "-w", Long: "--watch", Description: "watch for changes", Danger: Safe},
			"--watch":       {Long: "--watch", Description: "watch for changes", Danger: Safe},
			"--dry-run":     {Long: "--dry-run", Description: "submit server-side dry run", Danger: Safe},
			"-it":           {Short: "-it", Description: "interactive terminal in container", Danger: Safe},
			"--replicas":    {Long: "--replicas", Description: "number of replicas", Danger: Caution},
			"--cascade":     {Long: "--cascade", Description: "cascade deletion to dependents", Danger: Destructive},
			"--context":     {Long: "--context", Description: "kubeconfig context to use", Danger: Safe},
			"--kubeconfig":  {Long: "--kubeconfig", Description: "path to kubeconfig file", Danger: Safe},
			"-c":            {Short: "-c", Long: "--container", Description: "target container name", Danger: Safe},
			"--tail":        {Long: "--tail", Description: "show last N log lines", Danger: Safe},
			"--since":       {Long: "--since", Description: "show logs since duration (e.g. 1h)", Danger: Safe},
			"--previous":    {Long: "--previous", Description: "show logs from previous container instance", Danger: Safe},
		},
	},
	"ssh": {
		Name:        "ssh",
		Description: "secure shell remote login",
		Flags: map[string]FlagInfo{
			"-p":  {Short: "-p", Description: "connect to port", Danger: Safe},
			"-i":  {Short: "-i", Description: "identity file (private key)", Danger: Safe},
			"-L":  {Short: "-L", Description: "local port forwarding (local:host:remote)", Danger: Safe},
			"-R":  {Short: "-R", Description: "remote port forwarding (remote:host:local)", Danger: Safe},
			"-D":  {Short: "-D", Description: "dynamic SOCKS proxy", Danger: Safe},
			"-N":  {Short: "-N", Description: "no remote command (port forwarding only)", Danger: Safe},
			"-f":  {Short: "-f", Description: "go to background after authentication", Danger: Safe},
			"-v":  {Short: "-v", Description: "verbose mode", Danger: Safe},
			"-vv": {Short: "-vv", Description: "very verbose mode", Danger: Safe},
			"-A":  {Short: "-A", Description: "enable agent forwarding", Danger: Caution, Tip: "Agent forwarding exposes keys to remote host admin"},
			"-X":  {Short: "-X", Description: "enable X11 forwarding", Danger: Safe},
			"-C":  {Short: "-C", Description: "enable compression", Danger: Safe},
			"-o":  {Short: "-o", Description: "set SSH option", Danger: Safe},
			"-J":  {Short: "-J", Description: "jump host (ProxyJump)", Danger: Safe},
			"-t":  {Short: "-t", Description: "force pseudo-terminal allocation", Danger: Safe},
			"-q":  {Short: "-q", Description: "quiet mode", Danger: Safe},
		},
	},
	"scp": {
		Name:        "scp",
		Description: "secure copy between hosts",
		Flags: map[string]FlagInfo{
			"-r":  {Short: "-r", Description: "copy directories recursively", Danger: Safe},
			"-P":  {Short: "-P", Description: "connect to port", Danger: Safe},
			"-i":  {Short: "-i", Description: "identity file (private key)", Danger: Safe},
			"-C":  {Short: "-C", Description: "enable compression", Danger: Safe},
			"-p":  {Short: "-p", Description: "preserve timestamps and permissions", Danger: Safe},
			"-q":  {Short: "-q", Description: "quiet mode", Danger: Safe},
			"-v":  {Short: "-v", Description: "verbose mode", Danger: Safe},
		},
	},
	"rsync": {
		Name:        "rsync",
		Description: "fast, versatile file sync",
		Flags: map[string]FlagInfo{
			"-a":       {Short: "-a", Long: "--archive", Description: "archive mode (preserves permissions, symlinks, etc.)", Danger: Safe},
			"-v":       {Short: "-v", Long: "--verbose", Description: "verbose output", Danger: Safe},
			"-z":       {Short: "-z", Long: "--compress", Description: "compress during transfer", Danger: Safe},
			"-r":       {Short: "-r", Long: "--recursive", Description: "copy directories recursively", Danger: Safe},
			"-P":       {Short: "-P", Description: "show progress + keep partial transfers", Danger: Safe},
			"--progress": {Long: "--progress", Description: "show transfer progress", Danger: Safe},
			"--delete": {Long: "--delete", Description: "delete files in destination not in source", Danger: Destructive, Tip: "Use --dry-run first to preview deletions"},
			"--dry-run": {Long: "--dry-run", Description: "show what would be transferred", Danger: Safe},
			"-n":       {Short: "-n", Long: "--dry-run", Description: "show what would be transferred", Danger: Safe},
			"--exclude": {Long: "--exclude", Description: "exclude files matching pattern", Danger: Safe},
			"--include": {Long: "--include", Description: "include files matching pattern", Danger: Safe},
			"-e":       {Short: "-e", Description: "specify remote shell (e.g., 'ssh -p 2222')", Danger: Safe},
			"--partial": {Long: "--partial", Description: "keep partially transferred files", Danger: Safe},
			"--bwlimit": {Long: "--bwlimit", Description: "limit bandwidth in KB/s", Danger: Safe},
			"--checksum": {Long: "--checksum", Description: "use checksum instead of time+size", Danger: Safe},
		},
	},
	"curl": {
		Name:        "curl",
		Description: "transfer data with URLs",
		Flags: map[string]FlagInfo{
			"-X":  {Short: "-X", Long: "--request", Description: "HTTP method (GET/POST/PUT/DELETE)", Danger: Safe},
			"-H":  {Short: "-H", Long: "--header", Description: "add HTTP header", Danger: Safe},
			"-d":  {Short: "-d", Long: "--data", Description: "send POST data", Danger: Safe},
			"-o":  {Short: "-o", Long: "--output", Description: "write output to file", Danger: Safe},
			"-O":  {Short: "-O", Long: "--remote-name", Description: "save with remote filename", Danger: Safe},
			"-s":  {Short: "-s", Long: "--silent", Description: "silent mode (no progress)", Danger: Safe},
			"-S":  {Short: "-S", Long: "--show-error", Description: "show errors even in silent mode", Danger: Safe},
			"-L":  {Short: "-L", Long: "--location", Description: "follow redirects", Danger: Safe},
			"-k":  {Short: "-k", Long: "--insecure", Description: "skip TLS certificate verification", Danger: Caution, Tip: "Vulnerable to man-in-the-middle attacks"},
			"-v":  {Short: "-v", Long: "--verbose", Description: "verbose output (show request/response headers)", Danger: Safe},
			"-I":  {Short: "-I", Long: "--head", Description: "fetch headers only (HEAD request)", Danger: Safe},
			"-i":  {Short: "-i", Long: "--include", Description: "include response headers in output", Danger: Safe},
			"-F":  {Short: "-F", Long: "--form", Description: "multipart form data upload", Danger: Safe},
			"--connect-timeout": {Long: "--connect-timeout", Description: "maximum time to connect (seconds)", Danger: Safe},
			"-m":  {Short: "-m", Long: "--max-time", Description: "maximum total time (seconds)", Danger: Safe},
			"--retry": {Long: "--retry", Description: "number of retries", Danger: Safe},
			"-w":  {Short: "-w", Long: "--write-out", Description: "output format after completion", Danger: Safe},
			"-b":  {Short: "-b", Long: "--cookie", Description: "send cookie", Danger: Safe},
			"-c":  {Short: "-c", Long: "--cookie-jar", Description: "save cookies to file", Danger: Safe},
			"--compressed": {Long: "--compressed", Description: "request compressed response", Danger: Safe},
			"--data-raw": {Long: "--data-raw", Description: "send raw POST data", Danger: Safe},
			"-f":  {Short: "-f", Long: "--fail", Description: "fail silently on HTTP error", Danger: Safe},
		},
	},
	"wget": {
		Name:        "wget",
		Description: "non-interactive network downloader",
		Flags: map[string]FlagInfo{
			"-O":  {Short: "-O", Description: "output file name", Danger: Safe},
			"-q":  {Short: "-q", Description: "quiet mode", Danger: Safe},
			"-c":  {Short: "-c", Description: "continue partial download", Danger: Safe},
			"-r":  {Short: "-r", Description: "recursive download", Danger: Caution, Tip: "May download entire website"},
			"--mirror": {Long: "--mirror", Description: "mirror a website (recursive + timestamps)", Danger: Caution},
			"-P":  {Short: "-P", Description: "save to directory", Danger: Safe},
			"--no-check-certificate": {Long: "--no-check-certificate", Description: "skip TLS verification", Danger: Caution},
			"-b":  {Short: "-b", Description: "run in background", Danger: Safe},
			"--limit-rate": {Long: "--limit-rate", Description: "limit download speed", Danger: Safe},
		},
	},
	"chmod": {
		Name:        "chmod",
		Description: "change file permissions",
		Flags: map[string]FlagInfo{
			"-R":       {Short: "-R", Long: "--recursive", Description: "change permissions recursively", Danger: Caution, Tip: "Recursive permission changes can break things — double-check the path"},
			"-v":       {Short: "-v", Long: "--verbose", Description: "show each file being changed", Danger: Safe},
			"-c":       {Short: "-c", Long: "--changes", Description: "show only files that changed", Danger: Safe},
			"--reference": {Long: "--reference", Description: "use reference file's permissions", Danger: Safe},
		},
	},
	"chown": {
		Name:        "chown",
		Description: "change file owner and group",
		Flags: map[string]FlagInfo{
			"-R":       {Short: "-R", Long: "--recursive", Description: "change ownership recursively", Danger: Caution, Tip: "Recursive ownership changes can break system files"},
			"-v":       {Short: "-v", Long: "--verbose", Description: "show each file being changed", Danger: Safe},
			"-c":       {Short: "-c", Long: "--changes", Description: "show only files that changed", Danger: Safe},
			"--reference": {Long: "--reference", Description: "use reference file's ownership", Danger: Safe},
		},
	},
	"rm": {
		Name:        "rm",
		Description: "remove files or directories",
		Flags: map[string]FlagInfo{
			"-r":  {Short: "-r", Long: "--recursive", Description: "remove directories and their contents", Danger: Destructive, Tip: "Double-check path before recursive delete"},
			"-R":  {Short: "-R", Description: "remove directories recursively (same as -r)", Danger: Destructive},
			"-f":  {Short: "-f", Long: "--force", Description: "force removal without confirmation", Danger: Destructive, Tip: "Combined with -r this is extremely dangerous — no recovery possible"},
			"-rf": {Short: "-rf", Description: "force recursive removal", Danger: Destructive, Tip: "This permanently deletes everything under the target — NO RECOVERY"},
			"-i":  {Short: "-i", Description: "prompt before each removal", Danger: Safe},
			"-I":  {Short: "-I", Description: "prompt once before removing many files", Danger: Safe},
			"-v":  {Short: "-v", Long: "--verbose", Description: "show files being removed", Danger: Safe},
			"-d":  {Short: "-d", Long: "--dir", Description: "remove empty directories", Danger: Caution},
		},
	},
	"cp": {
		Name:        "cp",
		Description: "copy files and directories",
		Flags: map[string]FlagInfo{
			"-r":  {Short: "-r", Long: "--recursive", Description: "copy directories recursively", Danger: Safe},
			"-R":  {Short: "-R", Description: "copy recursively (same as -r)", Danger: Safe},
			"-i":  {Short: "-i", Long: "--interactive", Description: "prompt before overwrite", Danger: Safe},
			"-f":  {Short: "-f", Long: "--force", Description: "force overwrite", Danger: Caution},
			"-v":  {Short: "-v", Long: "--verbose", Description: "show files being copied", Danger: Safe},
			"-p":  {Short: "-p", Description: "preserve permissions and timestamps", Danger: Safe},
			"-a":  {Short: "-a", Long: "--archive", Description: "archive mode (preserve all attributes)", Danger: Safe},
			"-l":  {Short: "-l", Long: "--link", Description: "hard-link instead of copy", Danger: Safe},
			"-s":  {Short: "-s", Long: "--symbolic-link", Description: "create symbolic links", Danger: Safe},
			"-u":  {Short: "-u", Long: "--update", Description: "copy only when source is newer", Danger: Safe},
			"-n":  {Short: "-n", Long: "--no-clobber", Description: "don't overwrite existing files", Danger: Safe},
		},
	},
	"mv": {
		Name:        "mv",
		Description: "move or rename files",
		Flags: map[string]FlagInfo{
			"-i":  {Short: "-i", Long: "--interactive", Description: "prompt before overwrite", Danger: Safe},
			"-f":  {Short: "-f", Long: "--force", Description: "force overwrite without prompt", Danger: Caution},
			"-v":  {Short: "-v", Long: "--verbose", Description: "show files being moved", Danger: Safe},
			"-n":  {Short: "-n", Long: "--no-clobber", Description: "don't overwrite existing files", Danger: Safe},
			"-u":  {Short: "-u", Long: "--update", Description: "move only when source is newer", Danger: Safe},
		},
	},
	"ls": {
		Name:        "ls",
		Description: "list directory contents",
		Flags: map[string]FlagInfo{
			"-l":  {Short: "-l", Description: "long listing format", Danger: Safe},
			"-a":  {Short: "-a", Long: "--all", Description: "show hidden files (starting with .)", Danger: Safe},
			"-la": {Short: "-la", Description: "long listing including hidden files", Danger: Safe},
			"-lh": {Short: "-lh", Description: "long listing with human-readable sizes", Danger: Safe},
			"-R":  {Short: "-R", Long: "--recursive", Description: "list subdirectories recursively", Danger: Safe},
			"-t":  {Short: "-t", Description: "sort by modification time", Danger: Safe},
			"-S":  {Short: "-S", Description: "sort by file size", Danger: Safe},
			"-r":  {Short: "-r", Long: "--reverse", Description: "reverse sort order", Danger: Safe},
			"-h":  {Short: "-h", Long: "--human-readable", Description: "human-readable sizes", Danger: Safe},
			"-1":  {Short: "-1", Description: "one file per line", Danger: Safe},
			"--color": {Long: "--color", Description: "colorize output", Danger: Safe},
		},
	},
	"du": {
		Name:        "du",
		Description: "estimate file space usage",
		Flags: map[string]FlagInfo{
			"-h":  {Short: "-h", Long: "--human-readable", Description: "human-readable sizes", Danger: Safe},
			"-s":  {Short: "-s", Long: "--summarize", Description: "show total for each argument", Danger: Safe},
			"-a":  {Short: "-a", Long: "--all", Description: "show counts for all files", Danger: Safe},
			"-d":  {Short: "-d", Long: "--max-depth", Description: "limit directory depth", Danger: Safe},
			"--max-depth": {Long: "--max-depth", Description: "limit directory depth", Danger: Safe},
			"-c":  {Short: "-c", Long: "--total", Description: "produce a grand total", Danger: Safe},
			"--exclude": {Long: "--exclude", Description: "exclude files matching pattern", Danger: Safe},
		},
	},
	"df": {
		Name:        "df",
		Description: "report filesystem disk space usage",
		Flags: map[string]FlagInfo{
			"-h":  {Short: "-h", Long: "--human-readable", Description: "human-readable sizes", Danger: Safe},
			"-T":  {Short: "-T", Long: "--print-type", Description: "show filesystem type", Danger: Safe},
			"-i":  {Short: "-i", Long: "--inodes", Description: "show inode usage", Danger: Safe},
			"-a":  {Short: "-a", Long: "--all", Description: "include pseudo filesystems", Danger: Safe},
		},
	},
	"ps": {
		Name:        "ps",
		Description: "report running processes",
		Flags: map[string]FlagInfo{
			"-e":   {Short: "-e", Description: "show all processes", Danger: Safe},
			"-f":   {Short: "-f", Description: "full format listing", Danger: Safe},
			"-u":   {Short: "-u", Description: "show processes for user", Danger: Safe},
			"aux":  {Long: "aux", Description: "show all processes with details (BSD syntax)", Danger: Safe},
			"-ef":  {Short: "-ef", Description: "show all processes in full format", Danger: Safe},
			"-p":   {Short: "-p", Description: "show specific process by PID", Danger: Safe},
			"--sort": {Long: "--sort", Description: "sort by field", Danger: Safe},
			"-o":   {Short: "-o", Description: "custom output format", Danger: Safe},
		},
	},
	"kill": {
		Name:        "kill",
		Description: "send signal to a process",
		Flags: map[string]FlagInfo{
			"-9":     {Short: "-9", Description: "send SIGKILL (force terminate — no cleanup)", Danger: Destructive, Tip: "Use SIGTERM (-15) first to allow graceful shutdown"},
			"-15":    {Short: "-15", Description: "send SIGTERM (graceful termination)", Danger: Caution},
			"-KILL":  {Long: "-KILL", Description: "force terminate (SIGKILL)", Danger: Destructive},
			"-TERM":  {Long: "-TERM", Description: "graceful termination (SIGTERM)", Danger: Caution},
			"-HUP":   {Long: "-HUP", Description: "send SIGHUP (reload config)", Danger: Safe},
			"-l":     {Short: "-l", Description: "list signal names", Danger: Safe},
		},
	},
	"xargs": {
		Name:        "xargs",
		Description: "build and execute commands from stdin",
		Flags: map[string]FlagInfo{
			"-0":  {Short: "-0", Description: "input items are null-delimited", Danger: Safe},
			"-I":  {Short: "-I", Description: "replace string in command", Danger: Safe},
			"-n":  {Short: "-n", Description: "max arguments per command", Danger: Safe},
			"-P":  {Short: "-P", Description: "max parallel processes", Danger: Safe},
			"-p":  {Short: "-p", Description: "prompt before execution", Danger: Safe},
			"-t":  {Short: "-t", Description: "print commands before execution", Danger: Safe},
			"-d":  {Short: "-d", Description: "input delimiter", Danger: Safe},
		},
	},
	"sort": {
		Name:        "sort",
		Description: "sort lines of text",
		Flags: map[string]FlagInfo{
			"-r":  {Short: "-r", Long: "--reverse", Description: "reverse sort order", Danger: Safe},
			"-n":  {Short: "-n", Long: "--numeric-sort", Description: "sort numerically", Danger: Safe},
			"-k":  {Short: "-k", Long: "--key", Description: "sort by specific field", Danger: Safe},
			"-t":  {Short: "-t", Long: "--field-separator", Description: "set field separator", Danger: Safe},
			"-u":  {Short: "-u", Long: "--unique", Description: "output unique lines only", Danger: Safe},
			"-h":  {Short: "-h", Long: "--human-numeric-sort", Description: "sort human-readable numbers (1K, 2M)", Danger: Safe},
			"-o":  {Short: "-o", Long: "--output", Description: "write output to file", Danger: Safe},
		},
	},
	"cut": {
		Name:        "cut",
		Description: "remove sections from each line",
		Flags: map[string]FlagInfo{
			"-d":  {Short: "-d", Long: "--delimiter", Description: "set field delimiter", Danger: Safe},
			"-f":  {Short: "-f", Long: "--fields", Description: "select fields", Danger: Safe},
			"-c":  {Short: "-c", Long: "--characters", Description: "select characters", Danger: Safe},
			"-b":  {Short: "-b", Long: "--bytes", Description: "select bytes", Danger: Safe},
			"--complement": {Long: "--complement", Description: "select complement of fields", Danger: Safe},
		},
	},
	"wc": {
		Name:        "wc",
		Description: "count lines, words, and bytes",
		Flags: map[string]FlagInfo{
			"-l":  {Short: "-l", Long: "--lines", Description: "count lines", Danger: Safe},
			"-w":  {Short: "-w", Long: "--words", Description: "count words", Danger: Safe},
			"-c":  {Short: "-c", Long: "--bytes", Description: "count bytes", Danger: Safe},
			"-m":  {Short: "-m", Long: "--chars", Description: "count characters", Danger: Safe},
		},
	},
	"head": {
		Name:        "head",
		Description: "output first part of files",
		Flags: map[string]FlagInfo{
			"-n":  {Short: "-n", Long: "--lines", Description: "output first N lines", Danger: Safe},
			"-c":  {Short: "-c", Long: "--bytes", Description: "output first N bytes", Danger: Safe},
		},
	},
	"tail": {
		Name:        "tail",
		Description: "output last part of files",
		Flags: map[string]FlagInfo{
			"-n":  {Short: "-n", Long: "--lines", Description: "output last N lines", Danger: Safe},
			"-f":  {Short: "-f", Long: "--follow", Description: "follow file as it grows", Danger: Safe},
			"-F":  {Short: "-F", Description: "follow with retry (handles log rotation)", Danger: Safe},
			"-c":  {Short: "-c", Long: "--bytes", Description: "output last N bytes", Danger: Safe},
		},
	},
	"cat": {
		Name:        "cat",
		Description: "concatenate and display files",
		Flags: map[string]FlagInfo{
			"-n":  {Short: "-n", Long: "--number", Description: "number all output lines", Danger: Safe},
			"-b":  {Short: "-b", Long: "--number-nonblank", Description: "number non-blank lines", Danger: Safe},
			"-s":  {Short: "-s", Long: "--squeeze-blank", Description: "squeeze multiple blank lines", Danger: Safe},
			"-A":  {Short: "-A", Long: "--show-all", Description: "show all non-printing characters", Danger: Safe},
		},
	},
	"mkdir": {
		Name:        "mkdir",
		Description: "create directories",
		Flags: map[string]FlagInfo{
			"-p":  {Short: "-p", Long: "--parents", Description: "create parent directories as needed", Danger: Safe},
			"-v":  {Short: "-v", Long: "--verbose", Description: "show created directories", Danger: Safe},
			"-m":  {Short: "-m", Long: "--mode", Description: "set permissions", Danger: Safe},
		},
	},
	"ln": {
		Name:        "ln",
		Description: "create links between files",
		Flags: map[string]FlagInfo{
			"-s":  {Short: "-s", Long: "--symbolic", Description: "create symbolic link", Danger: Safe},
			"-f":  {Short: "-f", Long: "--force", Description: "force overwrite existing link", Danger: Caution},
			"-v":  {Short: "-v", Long: "--verbose", Description: "show links being created", Danger: Safe},
		},
	},
	"ssh-keygen": {
		Name:        "ssh-keygen",
		Description: "generate SSH key pairs",
		Flags: map[string]FlagInfo{
			"-t":  {Short: "-t", Description: "key type (rsa, ed25519, ecdsa)", Danger: Safe},
			"-b":  {Short: "-b", Description: "key bit length", Danger: Safe},
			"-C":  {Short: "-C", Description: "comment (usually email)", Danger: Safe},
			"-f":  {Short: "-f", Description: "output file path", Danger: Safe},
			"-N":  {Short: "-N", Description: "passphrase", Danger: Safe},
			"-R":  {Short: "-R", Description: "remove host from known_hosts", Danger: Safe},
			"-l":  {Short: "-l", Description: "show fingerprint", Danger: Safe},
		},
	},
	"systemctl": {
		Name:        "systemctl",
		Description: "manage systemd services",
		Subcommands: map[string]string{
			"start":   "start a service",
			"stop":    "stop a service",
			"restart": "restart a service",
			"reload":  "reload a service configuration",
			"enable":  "enable service at boot",
			"disable": "disable service at boot",
			"status":  "show service status",
			"list-units": "list active units",
			"daemon-reload": "reload systemd configuration",
			"is-active": "check if service is running",
			"is-enabled": "check if service is enabled",
			"mask":    "completely disable a service",
			"unmask":  "undo mask on a service",
		},
		Flags: map[string]FlagInfo{
			"--now":  {Long: "--now", Description: "start/stop immediately when enabling/disabling", Danger: Safe},
			"--user": {Long: "--user", Description: "operate on user services", Danger: Safe},
			"-l":     {Short: "-l", Description: "show full output (don't truncate)", Danger: Safe},
			"--no-pager": {Long: "--no-pager", Description: "don't pipe through pager", Danger: Safe},
			"--failed":  {Long: "--failed", Description: "show only failed units", Danger: Safe},
		},
	},
	"journalctl": {
		Name:        "journalctl",
		Description: "query the systemd journal",
		Flags: map[string]FlagInfo{
			"-u":      {Short: "-u", Description: "show logs for specific unit", Danger: Safe},
			"-f":      {Short: "-f", Long: "--follow", Description: "follow new log entries", Danger: Safe},
			"-n":      {Short: "-n", Long: "--lines", Description: "show last N lines", Danger: Safe},
			"-b":      {Short: "-b", Description: "show logs from current boot", Danger: Safe},
			"--since": {Long: "--since", Description: "show logs since timestamp", Danger: Safe},
			"--until": {Long: "--until", Description: "show logs until timestamp", Danger: Safe},
			"-p":      {Short: "-p", Description: "filter by priority (emerg..debug)", Danger: Safe},
			"--no-pager": {Long: "--no-pager", Description: "don't pipe through pager", Danger: Safe},
			"-e":      {Short: "-e", Description: "jump to end of journal", Danger: Safe},
			"-x":      {Short: "-x", Description: "add message explanations", Danger: Safe},
			"--vacuum-size": {Long: "--vacuum-size", Description: "remove old logs to reach size", Danger: Caution},
			"--vacuum-time": {Long: "--vacuum-time", Description: "remove logs older than duration", Danger: Caution},
		},
	},
	"npm": {
		Name:        "npm",
		Description: "Node.js package manager",
		Subcommands: map[string]string{
			"install":   "install packages",
			"uninstall": "remove packages",
			"update":    "update packages",
			"init":      "create package.json",
			"run":       "run a script from package.json",
			"test":      "run test script",
			"start":     "run start script",
			"build":     "run build script",
			"publish":   "publish package to registry",
			"audit":     "run security audit",
			"outdated":  "check for outdated packages",
			"ls":        "list installed packages",
			"ci":        "clean install from lockfile",
			"cache":     "manage npm cache",
			"link":      "symlink a package folder",
			"pack":      "create a tarball from package",
			"version":   "bump package version",
			"exec":      "run a package binary (npx)",
		},
		Flags: map[string]FlagInfo{
			"-g":           {Short: "-g", Long: "--global", Description: "install globally", Danger: Safe},
			"--global":     {Long: "--global", Description: "install globally", Danger: Safe},
			"--save-dev":   {Long: "--save-dev", Description: "save as dev dependency", Danger: Safe},
			"-D":           {Short: "-D", Description: "save as dev dependency", Danger: Safe},
			"--save-exact": {Long: "--save-exact", Description: "save exact version", Danger: Safe},
			"--production": {Long: "--production", Description: "skip devDependencies", Danger: Safe},
			"--legacy-peer-deps": {Long: "--legacy-peer-deps", Description: "ignore peer dependency conflicts", Danger: Caution},
			"--force":      {Long: "--force", Description: "force install", Danger: Caution},
			"--dry-run":    {Long: "--dry-run", Description: "show what would happen", Danger: Safe},
		},
	},
	"pip": {
		Name:        "pip",
		Description: "Python package manager",
		Subcommands: map[string]string{
			"install":   "install packages",
			"uninstall": "remove packages",
			"freeze":    "output installed packages in requirements format",
			"list":      "list installed packages",
			"show":      "show package info",
			"search":    "search PyPI",
			"download":  "download packages",
			"check":     "verify installed packages have compatible deps",
		},
		Flags: map[string]FlagInfo{
			"-r":          {Short: "-r", Long: "--requirement", Description: "install from requirements file", Danger: Safe},
			"--requirement": {Long: "--requirement", Description: "install from requirements file", Danger: Safe},
			"-U":          {Short: "-U", Long: "--upgrade", Description: "upgrade package to latest", Danger: Safe},
			"--upgrade":   {Long: "--upgrade", Description: "upgrade package to latest", Danger: Safe},
			"--user":      {Long: "--user", Description: "install to user directory", Danger: Safe},
			"-e":          {Short: "-e", Long: "--editable", Description: "install in editable/development mode", Danger: Safe},
			"--no-deps":   {Long: "--no-deps", Description: "don't install dependencies", Danger: Caution},
			"--force-reinstall": {Long: "--force-reinstall", Description: "force reinstall even if up-to-date", Danger: Safe},
			"--no-cache-dir": {Long: "--no-cache-dir", Description: "disable pip cache", Danger: Safe},
			"-y":          {Short: "-y", Long: "--yes", Description: "don't ask for confirmation", Danger: Safe},
		},
	},
	"go": {
		Name:        "go",
		Description: "Go programming language tool",
		Subcommands: map[string]string{
			"build":   "compile packages and dependencies",
			"run":     "compile and run Go program",
			"test":    "run tests",
			"get":     "add dependencies to current module",
			"mod":     "module maintenance",
			"fmt":     "format Go source code",
			"vet":     "report likely mistakes in Go code",
			"install": "compile and install packages",
			"clean":   "remove object files and cached files",
			"doc":     "show documentation",
			"env":     "print Go environment information",
			"generate": "generate Go files by processing source",
			"work":    "workspace maintenance",
			"tool":    "run specified Go tool",
		},
		Flags: map[string]FlagInfo{
			"-v":       {Short: "-v", Description: "verbose output", Danger: Safe},
			"-race":    {Long: "-race", Description: "enable race detector", Danger: Safe},
			"-count":   {Long: "-count", Description: "run each test N times", Danger: Safe},
			"-run":     {Long: "-run", Description: "run only matching tests", Danger: Safe},
			"-bench":   {Long: "-bench", Description: "run matching benchmarks", Danger: Safe},
			"-cover":   {Long: "-cover", Description: "enable coverage analysis", Danger: Safe},
			"-o":       {Short: "-o", Description: "output file name", Danger: Safe},
			"-ldflags": {Long: "-ldflags", Description: "linker flags", Danger: Safe},
			"-tags":    {Long: "-tags", Description: "build tags", Danger: Safe},
			"-mod":     {Long: "-mod", Description: "module download mode", Danger: Safe},
			"./...":    {Long: "./...", Description: "all packages recursively", Danger: Safe},
		},
	},
	"cargo": {
		Name:        "cargo",
		Description: "Rust package manager and build tool",
		Subcommands: map[string]string{
			"build":   "compile the current package",
			"run":     "build and run",
			"test":    "run tests",
			"new":     "create a new Cargo package",
			"init":    "create a new package in existing directory",
			"add":     "add dependency to Cargo.toml",
			"remove":  "remove dependency",
			"update":  "update dependencies",
			"publish": "publish package to crates.io",
			"doc":     "build documentation",
			"clean":   "remove build artifacts",
			"check":   "check for errors without building",
			"clippy":  "run linter",
			"fmt":     "format code",
			"bench":   "run benchmarks",
		},
		Flags: map[string]FlagInfo{
			"--release": {Long: "--release", Description: "build in release mode (optimized)", Danger: Safe},
			"-p":       {Short: "-p", Long: "--package", Description: "target specific package", Danger: Safe},
			"--all":    {Long: "--all", Description: "build all packages in workspace", Danger: Safe},
			"--features": {Long: "--features", Description: "enable specific features", Danger: Safe},
			"--no-default-features": {Long: "--no-default-features", Description: "disable default features", Danger: Safe},
			"--target": {Long: "--target", Description: "cross-compile target", Danger: Safe},
		},
	},
	"apt": {
		Name:        "apt",
		Description: "Debian/Ubuntu package manager",
		Subcommands: map[string]string{
			"install":    "install packages",
			"remove":     "remove packages",
			"purge":      "remove packages and configuration",
			"update":     "update package index",
			"upgrade":    "upgrade installed packages",
			"autoremove": "remove unused dependencies",
			"search":     "search for packages",
			"show":       "show package details",
			"list":       "list packages",
			"full-upgrade": "upgrade with dependency handling",
			"edit-sources": "edit sources.list",
		},
		Flags: map[string]FlagInfo{
			"-y":      {Short: "-y", Long: "--yes", Description: "assume yes to prompts", Danger: Caution},
			"--yes":   {Long: "--yes", Description: "assume yes to prompts", Danger: Caution},
			"--dry-run": {Long: "--dry-run", Description: "show what would happen", Danger: Safe},
			"--no-install-recommends": {Long: "--no-install-recommends", Description: "skip recommended packages", Danger: Safe},
			"--purge": {Long: "--purge", Description: "also remove configuration files", Danger: Destructive},
			"--fix-broken": {Long: "--fix-broken", Description: "fix broken dependencies", Danger: Safe},
		},
	},
	"brew": {
		Name:        "brew",
		Description: "macOS/Linux package manager (Homebrew)",
		Subcommands: map[string]string{
			"install":  "install a formula/cask",
			"uninstall": "uninstall a formula/cask",
			"update":   "update Homebrew and formulae list",
			"upgrade":  "upgrade installed formulae",
			"search":   "search for formulae",
			"info":     "show formula info",
			"list":     "list installed formulae",
			"cleanup":  "remove old versions",
			"doctor":   "check system for issues",
			"services": "manage background services",
			"tap":      "add a third-party repository",
			"untap":    "remove a third-party repository",
			"pin":      "prevent formula from being upgraded",
			"unpin":    "allow formula to be upgraded again",
			"link":     "symlink formula files",
			"unlink":   "remove formula symlinks",
		},
		Flags: map[string]FlagInfo{
			"--cask":  {Long: "--cask", Description: "install as cask (GUI app)", Danger: Safe},
			"--force": {Long: "--force", Description: "force operation", Danger: Caution},
			"--dry-run": {Long: "--dry-run", Description: "show what would happen", Danger: Safe},
		},
	},
	"helm": {
		Name:        "helm",
		Description: "Kubernetes package manager",
		Subcommands: map[string]string{
			"install":  "install a chart",
			"uninstall": "uninstall a release",
			"upgrade":  "upgrade a release",
			"rollback": "rollback a release to a previous revision",
			"list":     "list releases",
			"repo":     "manage chart repositories",
			"search":   "search for charts",
			"show":     "show chart info",
			"template": "render chart templates locally",
			"lint":     "examine a chart for issues",
			"package":  "package a chart directory",
			"pull":     "download a chart",
			"create":   "create a new chart",
			"status":   "display release status",
			"history":  "show release history",
		},
		Flags: map[string]FlagInfo{
			"-n":         {Short: "-n", Long: "--namespace", Description: "target namespace", Danger: Safe},
			"--namespace": {Long: "--namespace", Description: "target namespace", Danger: Safe},
			"-f":         {Short: "-f", Long: "--values", Description: "values file", Danger: Safe},
			"--set":      {Long: "--set", Description: "set values on command line", Danger: Safe},
			"--dry-run":  {Long: "--dry-run", Description: "simulate install/upgrade", Danger: Safe},
			"--wait":     {Long: "--wait", Description: "wait for pods to be ready", Danger: Safe},
			"--timeout":  {Long: "--timeout", Description: "operation timeout", Danger: Safe},
			"--create-namespace": {Long: "--create-namespace", Description: "create namespace if not exists", Danger: Safe},
		},
	},
	"terraform": {
		Name:        "terraform",
		Description: "infrastructure as code tool",
		Subcommands: map[string]string{
			"init":     "initialize Terraform working directory",
			"plan":     "preview changes to infrastructure",
			"apply":    "apply changes to infrastructure",
			"destroy":  "destroy managed infrastructure",
			"fmt":      "format configuration files",
			"validate": "validate configuration",
			"output":   "show output values",
			"state":    "manage state",
			"import":   "import existing infrastructure",
			"workspace": "manage workspaces",
			"refresh":  "update state with real infrastructure",
			"graph":    "generate dependency graph",
			"taint":    "mark resource for recreation",
			"untaint":  "remove taint from resource",
		},
		Flags: map[string]FlagInfo{
			"-auto-approve": {Long: "-auto-approve", Description: "skip approval prompt", Danger: Destructive, Tip: "Review the plan before applying without approval"},
			"-var":         {Long: "-var", Description: "set a variable", Danger: Safe},
			"-var-file":    {Long: "-var-file", Description: "variable file", Danger: Safe},
			"-target":      {Long: "-target", Description: "target specific resource", Danger: Caution},
			"-lock":        {Long: "-lock", Description: "lock state during operations", Danger: Safe},
			"-parallelism": {Long: "-parallelism", Description: "number of concurrent operations", Danger: Safe},
			"-state":       {Long: "-state", Description: "path to state file", Danger: Safe},
			"-out":         {Long: "-out", Description: "save plan to file", Danger: Safe},
		},
	},
	"make": {
		Name:        "make",
		Description: "build automation tool",
		Flags: map[string]FlagInfo{
			"-j":  {Short: "-j", Description: "number of parallel jobs", Danger: Safe},
			"-f":  {Short: "-f", Description: "specify Makefile", Danger: Safe},
			"-n":  {Short: "-n", Long: "--dry-run", Description: "print commands without executing", Danger: Safe},
			"-B":  {Short: "-B", Long: "--always-make", Description: "unconditionally make all targets", Danger: Safe},
			"-C":  {Short: "-C", Description: "change to directory before reading Makefile", Danger: Safe},
			"-k":  {Short: "-k", Long: "--keep-going", Description: "continue on errors", Danger: Safe},
			"-s":  {Short: "-s", Long: "--silent", Description: "don't echo commands", Danger: Safe},
		},
	},
	"lsof": {
		Name:        "lsof",
		Description: "list open files",
		Flags: map[string]FlagInfo{
			"-i":  {Short: "-i", Description: "list internet connections (optionally filter by port)", Danger: Safe},
			"-t":  {Short: "-t", Description: "terse output (PIDs only)", Danger: Safe},
			"-p":  {Short: "-p", Description: "filter by process ID", Danger: Safe},
			"-u":  {Short: "-u", Description: "filter by user", Danger: Safe},
			"-c":  {Short: "-c", Description: "filter by command name", Danger: Safe},
			"+D":  {Long: "+D", Description: "search directory tree", Danger: Safe},
		},
	},
	"netstat": {
		Name:        "netstat",
		Description: "network statistics",
		Flags: map[string]FlagInfo{
			"-t":     {Short: "-t", Description: "TCP connections", Danger: Safe},
			"-u":     {Short: "-u", Description: "UDP connections", Danger: Safe},
			"-l":     {Short: "-l", Description: "listening sockets only", Danger: Safe},
			"-n":     {Short: "-n", Description: "numeric addresses (don't resolve)", Danger: Safe},
			"-p":     {Short: "-p", Description: "show process PID/name", Danger: Safe},
			"-tulnp": {Short: "-tulnp", Description: "common combo: TCP+UDP, listening, numeric, with PIDs", Danger: Safe},
			"-a":     {Short: "-a", Description: "all connections", Danger: Safe},
		},
	},
	"ss": {
		Name:        "ss",
		Description: "socket statistics (modern netstat replacement)",
		Flags: map[string]FlagInfo{
			"-t":  {Short: "-t", Description: "TCP sockets", Danger: Safe},
			"-u":  {Short: "-u", Description: "UDP sockets", Danger: Safe},
			"-l":  {Short: "-l", Description: "listening sockets", Danger: Safe},
			"-n":  {Short: "-n", Description: "numeric addresses", Danger: Safe},
			"-p":  {Short: "-p", Description: "show process using socket", Danger: Safe},
			"-a":  {Short: "-a", Description: "all sockets", Danger: Safe},
			"-s":  {Short: "-s", Description: "summary statistics", Danger: Safe},
		},
	},
	"iptables": {
		Name:        "iptables",
		Description: "IPv4 firewall administration",
		Flags: map[string]FlagInfo{
			"-A":  {Short: "-A", Description: "append rule to chain", Danger: Caution},
			"-D":  {Short: "-D", Description: "delete rule from chain", Danger: Caution},
			"-I":  {Short: "-I", Description: "insert rule at position", Danger: Caution},
			"-L":  {Short: "-L", Description: "list rules", Danger: Safe},
			"-F":  {Short: "-F", Description: "flush all rules in chain", Danger: Destructive, Tip: "This removes ALL firewall rules — may lock you out of remote servers"},
			"-X":  {Short: "-X", Description: "delete user-defined chain", Danger: Destructive},
			"-P":  {Short: "-P", Description: "set default policy", Danger: Destructive, Tip: "Setting default to DROP can lock you out of SSH"},
			"-p":  {Short: "-p", Description: "protocol (tcp/udp/icmp)", Danger: Safe},
			"--dport": {Long: "--dport", Description: "destination port", Danger: Safe},
			"--sport": {Long: "--sport", Description: "source port", Danger: Safe},
			"-s":  {Short: "-s", Description: "source address", Danger: Safe},
			"-d":  {Short: "-d", Description: "destination address", Danger: Safe},
			"-j":  {Short: "-j", Description: "target action (ACCEPT/DROP/REJECT)", Danger: Caution},
			"-n":  {Short: "-n", Description: "numeric output", Danger: Safe},
			"-v":  {Short: "-v", Description: "verbose output", Danger: Safe},
			"--line-numbers": {Long: "--line-numbers", Description: "show rule numbers", Danger: Safe},
		},
	},
	"openssl": {
		Name:        "openssl",
		Description: "cryptography and SSL/TLS toolkit",
		Flags: map[string]FlagInfo{
			"-newkey":  {Long: "-newkey", Description: "generate new key (e.g., rsa:2048)", Danger: Safe},
			"-x509":    {Long: "-x509", Description: "output self-signed certificate", Danger: Safe},
			"-days":    {Long: "-days", Description: "certificate validity period", Danger: Safe},
			"-out":     {Long: "-out", Description: "output file", Danger: Safe},
			"-keyout":  {Long: "-keyout", Description: "key output file", Danger: Safe},
			"-nodes":   {Long: "-nodes", Description: "no DES encryption on key", Danger: Caution},
			"-subj":    {Long: "-subj", Description: "certificate subject", Danger: Safe},
			"-in":      {Long: "-in", Description: "input file", Danger: Safe},
			"-text":    {Long: "-text", Description: "print in text form", Danger: Safe},
			"-noout":   {Long: "-noout", Description: "don't output the encoded version", Danger: Safe},
			"-sha256":  {Long: "-sha256", Description: "use SHA-256 digest", Danger: Safe},
		},
	},
	"ffmpeg": {
		Name:        "ffmpeg",
		Description: "multimedia processing tool",
		Flags: map[string]FlagInfo{
			"-i":       {Short: "-i", Description: "input file", Danger: Safe},
			"-o":       {Short: "-o", Description: "output file", Danger: Safe},
			"-c":       {Short: "-c", Description: "codec (copy/libx264/aac)", Danger: Safe},
			"-c:v":     {Short: "-c:v", Description: "video codec", Danger: Safe},
			"-c:a":     {Short: "-c:a", Description: "audio codec", Danger: Safe},
			"-vf":      {Short: "-vf", Description: "video filter (scale, crop, rotate)", Danger: Safe},
			"-af":      {Short: "-af", Description: "audio filter", Danger: Safe},
			"-ss":      {Short: "-ss", Description: "start time offset", Danger: Safe},
			"-t":       {Short: "-t", Description: "duration", Danger: Safe},
			"-to":      {Short: "-to", Description: "end time", Danger: Safe},
			"-crf":     {Short: "-crf", Description: "quality (0=lossless, 23=default, 51=worst)", Danger: Safe},
			"-preset":  {Long: "-preset", Description: "encoding speed/quality tradeoff", Danger: Safe},
			"-y":       {Short: "-y", Description: "overwrite output without asking", Danger: Caution},
			"-an":      {Short: "-an", Description: "disable audio", Danger: Safe},
			"-vn":      {Short: "-vn", Description: "disable video", Danger: Safe},
			"-r":       {Short: "-r", Description: "frame rate", Danger: Safe},
			"-b:v":     {Short: "-b:v", Description: "video bitrate", Danger: Safe},
			"-b:a":     {Short: "-b:a", Description: "audio bitrate", Danger: Safe},
		},
	},
	"zip": {
		Name:        "zip",
		Description: "package and compress files",
		Flags: map[string]FlagInfo{
			"-r":  {Short: "-r", Description: "recurse into directories", Danger: Safe},
			"-e":  {Short: "-e", Description: "encrypt archive", Danger: Safe},
			"-x":  {Short: "-x", Description: "exclude files", Danger: Safe},
			"-9":  {Short: "-9", Description: "best compression", Danger: Safe},
			"-q":  {Short: "-q", Description: "quiet mode", Danger: Safe},
			"-d":  {Short: "-d", Description: "delete entries from archive", Danger: Caution},
		},
	},
	"unzip": {
		Name:        "unzip",
		Description: "extract compressed files",
		Flags: map[string]FlagInfo{
			"-d":  {Short: "-d", Description: "extract to directory", Danger: Safe},
			"-o":  {Short: "-o", Description: "overwrite existing files", Danger: Caution},
			"-l":  {Short: "-l", Description: "list contents", Danger: Safe},
			"-q":  {Short: "-q", Description: "quiet mode", Danger: Safe},
		},
	},
	"gzip": {
		Name:        "gzip",
		Description: "compress or decompress files",
		Flags: map[string]FlagInfo{
			"-d":  {Short: "-d", Long: "--decompress", Description: "decompress", Danger: Safe},
			"-k":  {Short: "-k", Long: "--keep", Description: "keep original file", Danger: Safe},
			"-r":  {Short: "-r", Long: "--recursive", Description: "compress recursively", Danger: Safe},
			"-v":  {Short: "-v", Long: "--verbose", Description: "verbose output", Danger: Safe},
			"-9":  {Short: "-9", Long: "--best", Description: "best compression", Danger: Safe},
			"-1":  {Short: "-1", Long: "--fast", Description: "fastest compression", Danger: Safe},
			"-l":  {Short: "-l", Long: "--list", Description: "list compressed file contents", Danger: Safe},
			"-c":  {Short: "-c", Long: "--stdout", Description: "write to stdout", Danger: Safe},
		},
	},
	"ping": {
		Name:        "ping",
		Description: "send ICMP echo request to host",
		Flags: map[string]FlagInfo{
			"-c":  {Short: "-c", Description: "number of packets to send", Danger: Safe},
			"-i":  {Short: "-i", Description: "interval between packets (seconds)", Danger: Safe},
			"-t":  {Short: "-t", Description: "TTL (time to live)", Danger: Safe},
			"-W":  {Short: "-W", Description: "timeout in seconds", Danger: Safe},
			"-s":  {Short: "-s", Description: "packet size", Danger: Safe},
			"-q":  {Short: "-q", Description: "quiet output", Danger: Safe},
			"-f":  {Short: "-f", Description: "flood ping (requires root)", Danger: Destructive, Tip: "Flood ping can overwhelm the network"},
		},
	},
	"ip": {
		Name:        "ip",
		Description: "show/manipulate network configuration",
		Subcommands: map[string]string{
			"addr":  "display/modify IP addresses",
			"link":  "display/modify network interfaces",
			"route": "display/modify routing table",
			"neigh": "display/modify ARP table",
			"rule":  "display/modify routing rules",
		},
		Flags: map[string]FlagInfo{
			"-4":  {Short: "-4", Description: "IPv4 only", Danger: Safe},
			"-6":  {Short: "-6", Description: "IPv6 only", Danger: Safe},
			"-s":  {Short: "-s", Description: "statistics", Danger: Safe},
			"-br": {Short: "-br", Description: "brief output", Danger: Safe},
		},
	},
	"crontab": {
		Name:        "crontab",
		Description: "manage user cron jobs",
		Flags: map[string]FlagInfo{
			"-l":  {Short: "-l", Description: "list current crontab", Danger: Safe},
			"-e":  {Short: "-e", Description: "edit crontab", Danger: Safe},
			"-r":  {Short: "-r", Description: "remove all cron jobs", Danger: Destructive, Tip: "This removes ALL cron jobs — use -l first to review"},
			"-u":  {Short: "-u", Description: "specify user", Danger: Safe},
		},
	},
	"dd": {
		Name:        "dd",
		Description: "convert and copy a file",
		Flags: map[string]FlagInfo{
			"if=":    {Long: "if=", Description: "input file", Danger: Safe},
			"of=":    {Long: "of=", Description: "output file", Danger: Destructive, Tip: "Writing to the wrong device can destroy data — double-check of="},
			"bs=":    {Long: "bs=", Description: "block size", Danger: Safe},
			"count=": {Long: "count=", Description: "number of blocks to copy", Danger: Safe},
			"status=": {Long: "status=", Description: "output level (none/noxfer/progress)", Danger: Safe},
			"conv=":  {Long: "conv=", Description: "conversion (notrunc, sync, etc.)", Danger: Caution},
		},
	},
}

// GetToolInfo returns the ToolInfo for a given binary name, or nil if not found.
func GetToolInfo(binary string) *ToolInfo {
	if info, ok := flagDB[binary]; ok {
		return &info
	}
	return nil
}

// GetFlagInfo returns the flag description for a specific tool and flag.
func GetFlagInfo(binary, flag string) *FlagInfo {
	tool, ok := flagDB[binary]
	if !ok {
		return nil
	}
	if info, ok := tool.Flags[flag]; ok {
		return &info
	}
	return nil
}

// GetSubcommandDescription returns the description for a tool's subcommand.
func GetSubcommandDescription(binary, subcommand string) string {
	tool, ok := flagDB[binary]
	if !ok {
		return ""
	}
	return tool.Subcommands[subcommand]
}

// IsDangerousFlag checks if a flag is destructive or requires caution.
func IsDangerousFlag(binary, flag string) (DangerLevel, string) {
	info := GetFlagInfo(binary, flag)
	if info == nil {
		return Safe, ""
	}
	return info.Danger, info.Tip
}

// ToolCount returns the number of tools in the database.
func ToolCount() int {
	return len(flagDB)
}
